### ISSUE TITLE
Chrome 54.x?

### ISSUE THREAD

**Issue by sustained** [Akujin/chromium-disable-profile-button-patch#1]
Has this been tested with 54.x?

**Comment by hparadiz** [comment]
The patch is likely broken but the point was more to document what to do rather than to maintain the patch indefinitely.

The current code is still using `BrowserView::ShouldShowAvatar()`.

Simply open `/chrome/browser/ui/views/frame/browser_view.cc` and find `bool BrowserView::ShouldShowAvatar() const` then make it return false and save -> compile.


tldr; don't use the patch, do it yourself with the patch as reference
